package vistas;

import controlador.ControladorBitacora;
import controlador.ControladorClientes;
import controlador.ControladorSistema;
import controlador.ControladorUsuarios;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.WindowConstants;

/**
 *
 * @author VICTOR
 */
public class ImprovementVistaSistema extends javax.swing.JFrame {

    public boolean CbxBitacoraAccio;

    /**
     * Creates new form VistaSistema
     */
    public ImprovementVistaSistema() {
        initComponents();
        setCustomIcon();
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    }
    
    private void setCustomIcon() {
        // Cargar el icono desde el archivo .png en la carpeta 'img'
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/iconcerdo.png"));
        setIconImage(icon); // Establecer el icono de la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        columaPanel = new javax.swing.JPanel();
        lblSistemaTitulo = new javax.swing.JLabel();
        btnSistemaVentas = new javax.swing.JButton();
        btnSistemaUsusarios = new javax.swing.JButton();
        btnSistemaProductos = new javax.swing.JButton();
        btnSistemaBitacora = new javax.swing.JButton();
        btnSistemaClientes = new javax.swing.JButton();
        btnSistemaNuevaVenta = new javax.swing.JButton();
        LOGO = new javax.swing.JLabel();
        tituloPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        vistasMultiple = new javax.swing.JTabbedPane();
        ventasPanel = new javax.swing.JPanel();
        UsuariosPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        containerData = new javax.swing.JPanel();
        txtUsuariosContrasena = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuariosId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUsuariosNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUsuariosApellidoMaterno = new javax.swing.JTextField();
        txtUsuariosApellidoPaterno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUsuariosUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnUsuariosRegistrar = new javax.swing.JButton();
        btnUsuariosLimpiar = new javax.swing.JButton();
        btnUsuariosModificar = new javax.swing.JButton();
        txtUsuariosEstado = new javax.swing.JTextField();
        btnUsuariosEstado = new javax.swing.JButton();
        BitacoraPanel = new javax.swing.JPanel();
        btnBitacoraBuscar = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        CbxBitacoraAccion = new javax.swing.JComboBox<>();
        cbxBitacoraSeccion = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        dateBiInicio = new com.toedter.calendar.JDateChooser();
        dateBFinal = new com.toedter.calendar.JDateChooser();
        btmBBuscar = new javax.swing.JButton();
        productosPanel = new javax.swing.JPanel();
        clientesPanel = new javax.swing.JPanel();
        contenedorDatos = new javax.swing.JPanel();
        txtClientesId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtClientesRfc = new javax.swing.JTextField();
        txtClientesApellidoMaterno = new javax.swing.JTextField();
        txtClientesNombre = new javax.swing.JTextField();
        txtClientesApellidoPaterno = new javax.swing.JTextField();
        txtClientesTelefono = new javax.swing.JTextField();
        txtClientesEstado = new javax.swing.JTextField();
        txtClientesCorreo = new javax.swing.JTextField();
        btnClientesRegistrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnClientesActualizar = new javax.swing.JButton();
        btnClientesLimpiar = new javax.swing.JButton();
        btnClientesEliminar = new javax.swing.JButton();
        btnClientesActivarDesactivar1 = new javax.swing.JButton();
        nuevaVentaPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuVentas = new javax.swing.JMenuItem();
        MenuProductos = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenuItem();
        menuBitacoras = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCerrarS = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        columaPanel.setBackground(new java.awt.Color(120, 0, 0));
        columaPanel.setForeground(new java.awt.Color(120, 0, 0));

        lblSistemaTitulo.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        lblSistemaTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblSistemaTitulo.setText("Sistema");

        btnSistemaVentas.setBackground(new java.awt.Color(120, 0, 0));
        btnSistemaVentas.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnSistemaVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnSistemaVentas.setText("VENTAS");
        btnSistemaVentas.setBorder(null);
        btnSistemaVentas.setBorderPainted(false);
        btnSistemaVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSistemaVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaVentasActionPerformed(evt);
            }
        });

        btnSistemaUsusarios.setBackground(new java.awt.Color(120, 0, 0));
        btnSistemaUsusarios.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnSistemaUsusarios.setForeground(new java.awt.Color(255, 255, 255));
        btnSistemaUsusarios.setText("USUARIOS");
        btnSistemaUsusarios.setBorder(null);
        btnSistemaUsusarios.setBorderPainted(false);
        btnSistemaUsusarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSistemaUsusarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaUsusariosActionPerformed(evt);
            }
        });

        btnSistemaProductos.setBackground(new java.awt.Color(120, 0, 0));
        btnSistemaProductos.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnSistemaProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnSistemaProductos.setText("PRODUCTOS");
        btnSistemaProductos.setBorder(null);
        btnSistemaProductos.setBorderPainted(false);
        btnSistemaProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSistemaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaProductosActionPerformed(evt);
            }
        });

        btnSistemaBitacora.setBackground(new java.awt.Color(120, 0, 0));
        btnSistemaBitacora.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnSistemaBitacora.setForeground(new java.awt.Color(255, 255, 255));
        btnSistemaBitacora.setText("BITACORA");
        btnSistemaBitacora.setBorder(null);
        btnSistemaBitacora.setBorderPainted(false);
        btnSistemaBitacora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSistemaBitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaBitacoraActionPerformed(evt);
            }
        });

        btnSistemaClientes.setBackground(new java.awt.Color(120, 0, 0));
        btnSistemaClientes.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnSistemaClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnSistemaClientes.setText("CLIENTES");
        btnSistemaClientes.setBorder(null);
        btnSistemaClientes.setBorderPainted(false);
        btnSistemaClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSistemaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaClientesActionPerformed(evt);
            }
        });

        btnSistemaNuevaVenta.setBackground(new java.awt.Color(120, 0, 0));
        btnSistemaNuevaVenta.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnSistemaNuevaVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnSistemaNuevaVenta.setText("NUEVA VENTA");
        btnSistemaNuevaVenta.setBorder(null);
        btnSistemaNuevaVenta.setBorderPainted(false);
        btnSistemaNuevaVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSistemaNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaNuevaVentaActionPerformed(evt);
            }
        });

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoC.png"))); // NOI18N
        LOGO.setText("jLabel2");
        LOGO.setMaximumSize(new java.awt.Dimension(160, 160));

        javax.swing.GroupLayout columaPanelLayout = new javax.swing.GroupLayout(columaPanel);
        columaPanel.setLayout(columaPanelLayout);
        columaPanelLayout.setHorizontalGroup(
            columaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, columaPanelLayout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(lblSistemaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, columaPanelLayout.createSequentialGroup()
                .addGroup(columaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSistemaVentas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSistemaUsusarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSistemaBitacora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSistemaProductos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSistemaClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSistemaNuevaVenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        columaPanelLayout.setVerticalGroup(
            columaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(columaPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblSistemaTitulo)
                .addGap(18, 18, 18)
                .addComponent(btnSistemaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSistemaUsusarios, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSistemaBitacora, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSistemaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSistemaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSistemaNuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(columaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 749));

        tituloPanel.setBackground(new java.awt.Color(193, 18, 31));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIENVENIDO");

        javax.swing.GroupLayout tituloPanelLayout = new javax.swing.GroupLayout(tituloPanel);
        tituloPanel.setLayout(tituloPanelLayout);
        tituloPanelLayout.setHorizontalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloPanelLayout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(257, 257, 257))
        );
        tituloPanelLayout.setVerticalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        bg.add(tituloPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 0, 800, -1));

        javax.swing.GroupLayout ventasPanelLayout = new javax.swing.GroupLayout(ventasPanel);
        ventasPanel.setLayout(ventasPanelLayout);
        ventasPanelLayout.setHorizontalGroup(
            ventasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        ventasPanelLayout.setVerticalGroup(
            ventasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );

        vistasMultiple.addTab("Ventas", ventasPanel);

        UsuariosPanel.setBackground(new java.awt.Color(120, 0, 0));
        UsuariosPanel.setForeground(new java.awt.Color(226, 95, 35));

        tblUsuarios.setForeground(new java.awt.Color(51, 51, 51));
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuario", "Nombre", "Apellido Paterno", "Apellido Materno", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        containerData.setBackground(new java.awt.Color(120, 0, 0));

        txtUsuariosContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuariosContrasenaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USUARIOS");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID");

        txtUsuariosId.setEditable(false);
        txtUsuariosId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuariosIdActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido paterno");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Usuario");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Apellido materno");

        txtUsuariosUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuariosUsuarioActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contraseña");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Estado");

        btnUsuariosRegistrar.setBackground(new java.awt.Color(193, 18, 31));
        btnUsuariosRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUsuariosRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuariosRegistrar.setText("Registrar");
        btnUsuariosRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUsuariosRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuariosRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosRegistrarActionPerformed(evt);
            }
        });

        btnUsuariosLimpiar.setBackground(new java.awt.Color(193, 18, 31));
        btnUsuariosLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUsuariosLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuariosLimpiar.setText("Limpiar");
        btnUsuariosLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUsuariosLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuariosLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosLimpiarActionPerformed(evt);
            }
        });

        btnUsuariosModificar.setBackground(new java.awt.Color(193, 18, 31));
        btnUsuariosModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUsuariosModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuariosModificar.setText("Modificar");
        btnUsuariosModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUsuariosModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuariosModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosModificarActionPerformed(evt);
            }
        });

        txtUsuariosEstado.setEditable(false);
        txtUsuariosEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuariosEstadoActionPerformed(evt);
            }
        });

        btnUsuariosEstado.setBackground(new java.awt.Color(193, 18, 31));
        btnUsuariosEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUsuariosEstado.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuariosEstado.setText("Estado");
        btnUsuariosEstado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUsuariosEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerDataLayout = new javax.swing.GroupLayout(containerData);
        containerData.setLayout(containerDataLayout);
        containerDataLayout.setHorizontalGroup(
            containerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerDataLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(containerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(containerDataLayout.createSequentialGroup()
                        .addGroup(containerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuariosId, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuariosNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuariosApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(containerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtUsuariosEstado, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUsuariosContrasena, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUsuariosUsuario)
                                .addComponent(txtUsuariosApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(containerDataLayout.createSequentialGroup()
                        .addGroup(containerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(containerDataLayout.createSequentialGroup()
                                .addComponent(btnUsuariosRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUsuariosLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerDataLayout.createSequentialGroup()
                                .addComponent(btnUsuariosEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btnUsuariosModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerDataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(27, 27, 27))
        );
        containerDataLayout.setVerticalGroup(
            containerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerDataLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(containerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuariosId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuariosNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addGroup(containerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerDataLayout.createSequentialGroup()
                        .addGroup(containerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsuariosApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerDataLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(containerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsuariosApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(13, 13, 13)
                        .addGroup(containerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsuariosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(10, 10, 10)
                        .addGroup(containerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsuariosContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(containerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsuariosEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(containerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUsuariosLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUsuariosRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(containerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUsuariosEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUsuariosModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout UsuariosPanelLayout = new javax.swing.GroupLayout(UsuariosPanel);
        UsuariosPanel.setLayout(UsuariosPanelLayout);
        UsuariosPanelLayout.setHorizontalGroup(
            UsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsuariosPanelLayout.createSequentialGroup()
                .addComponent(containerData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        UsuariosPanelLayout.setVerticalGroup(
            UsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsuariosPanelLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        vistasMultiple.addTab("Usuarios", UsuariosPanel);

        btnBitacoraBuscar.setBackground(new java.awt.Color(120, 0, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("BITACORA");

        jLabel19.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Accion");

        jLabel20.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Seccion");

        CbxBitacoraAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxBitacoraAccionActionPerformed(evt);
            }
        });

        cbxBitacoraSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBitacoraSeccionActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Inicio");

        jLabel23.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Final");

        btmBBuscar.setText("BUSCAR");
        btmBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmBBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnBitacoraBuscarLayout = new javax.swing.GroupLayout(btnBitacoraBuscar);
        btnBitacoraBuscar.setLayout(btnBitacoraBuscarLayout);
        btnBitacoraBuscarLayout.setHorizontalGroup(
            btnBitacoraBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBitacoraBuscarLayout.createSequentialGroup()
                .addGroup(btnBitacoraBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CbxBitacoraAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btnBitacoraBuscarLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnBitacoraBuscarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18)))
                .addGap(6, 6, 6)
                .addGroup(btnBitacoraBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(btnBitacoraBuscarLayout.createSequentialGroup()
                        .addComponent(cbxBitacoraSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dateBiInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnBitacoraBuscarLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGroup(btnBitacoraBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnBitacoraBuscarLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(dateBFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btmBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnBitacoraBuscarLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
        );
        btnBitacoraBuscarLayout.setVerticalGroup(
            btnBitacoraBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBitacoraBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnBitacoraBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(btnBitacoraBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btnBitacoraBuscarLayout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(btnBitacoraBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20)))
                        .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btnBitacoraBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(btnBitacoraBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CbxBitacoraAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxBitacoraSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateBiInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateBFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmBBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout BitacoraPanelLayout = new javax.swing.GroupLayout(BitacoraPanel);
        BitacoraPanel.setLayout(BitacoraPanelLayout);
        BitacoraPanelLayout.setHorizontalGroup(
            BitacoraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BitacoraPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBitacoraBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BitacoraPanelLayout.setVerticalGroup(
            BitacoraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBitacoraBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        vistasMultiple.addTab("Bitácora", BitacoraPanel);

        javax.swing.GroupLayout productosPanelLayout = new javax.swing.GroupLayout(productosPanel);
        productosPanel.setLayout(productosPanelLayout);
        productosPanelLayout.setHorizontalGroup(
            productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        productosPanelLayout.setVerticalGroup(
            productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );

        vistasMultiple.addTab("Productos", productosPanel);

        txtClientesId.setEditable(false);

        jLabel10.setText("ID");

        jLabel11.setText("Nombre");

        jLabel12.setText("RFC");

        jLabel13.setText("Apellido Paterno");

        jLabel14.setText("Apellido Materno");

        jLabel15.setText("Correo");

        jLabel16.setText("Teléfono");

        jLabel17.setText("Estado");

        txtClientesEstado.setEditable(false);

        btnClientesRegistrar.setText("Registrar");
        btnClientesRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesRegistrarActionPerformed(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "RFC", "Nombre", "Apellido Paterno", "Apellido Materno", "Correo", "Teléfono", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblClientes);

        btnClientesActualizar.setText("Actualizar");
        btnClientesActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActualizarActionPerformed(evt);
            }
        });

        btnClientesLimpiar.setText("Limpiar");
        btnClientesLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesLimpiarActionPerformed(evt);
            }
        });

        btnClientesEliminar.setText("Eliminar");
        btnClientesEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesEliminarActionPerformed(evt);
            }
        });

        btnClientesActivarDesactivar1.setText("Activar/Desactivar");
        btnClientesActivarDesactivar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActivarDesactivar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenedorDatosLayout = new javax.swing.GroupLayout(contenedorDatos);
        contenedorDatos.setLayout(contenedorDatosLayout);
        contenedorDatosLayout.setHorizontalGroup(
            contenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorDatosLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(contenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorDatosLayout.createSequentialGroup()
                        .addGroup(contenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenedorDatosLayout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtClientesEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorDatosLayout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtClientesTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorDatosLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtClientesCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorDatosLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(txtClientesApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorDatosLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtClientesRfc, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenedorDatosLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtClientesId, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenedorDatosLayout.createSequentialGroup()
                                .addGroup(contenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(contenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtClientesNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtClientesApellidoPaterno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(40, 40, 40))
                    .addGroup(contenedorDatosLayout.createSequentialGroup()
                        .addGroup(contenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenedorDatosLayout.createSequentialGroup()
                                .addGroup(contenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnClientesRegistrar)
                                    .addComponent(btnClientesLimpiar))
                                .addGap(18, 18, 18)
                                .addGroup(contenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnClientesActualizar)
                                    .addComponent(btnClientesActivarDesactivar1)))
                            .addComponent(btnClientesEliminar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        contenedorDatosLayout.setVerticalGroup(
            contenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorDatosLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(contenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClientesId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtClientesRfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtClientesNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtClientesApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtClientesApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtClientesCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtClientesTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtClientesEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(contenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClientesRegistrar)
                    .addComponent(btnClientesActualizar))
                .addGap(18, 18, 18)
                .addGroup(contenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClientesLimpiar)
                    .addComponent(btnClientesActivarDesactivar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClientesEliminar)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(contenedorDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout clientesPanelLayout = new javax.swing.GroupLayout(clientesPanel);
        clientesPanel.setLayout(clientesPanelLayout);
        clientesPanelLayout.setHorizontalGroup(
            clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedorDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        clientesPanelLayout.setVerticalGroup(
            clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedorDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        vistasMultiple.addTab("Clientes", clientesPanel);

        javax.swing.GroupLayout nuevaVentaPanelLayout = new javax.swing.GroupLayout(nuevaVentaPanel);
        nuevaVentaPanel.setLayout(nuevaVentaPanelLayout);
        nuevaVentaPanelLayout.setHorizontalGroup(
            nuevaVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        nuevaVentaPanelLayout.setVerticalGroup(
            nuevaVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );

        vistasMultiple.addTab("Nueva venta", nuevaVentaPanel);

        bg.add(vistasMultiple, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 800, 640));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jMenu1.setText("Operaciones");

        menuVentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuVentas.setText("Ventas");
        menuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVentasActionPerformed(evt);
            }
        });
        jMenu1.add(menuVentas);

        MenuProductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuProductos.setText("Productos");
        MenuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductosActionPerformed(evt);
            }
        });
        jMenu1.add(MenuProductos);

        menuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuUsuarios.setText("Usuarios");
        menuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(menuUsuarios);

        menuBitacoras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuBitacoras.setText("Bitacoras");
        menuBitacoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBitacorasActionPerformed(evt);
            }
        });
        jMenu1.add(menuBitacoras);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sesion");

        menuCerrarS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD9, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuCerrarS.setText("Cerrar Sesion");
        menuCerrarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarSActionPerformed(evt);
            }
        });
        jMenu2.add(menuCerrarS);

        menuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD0, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu2.add(menuSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductosActionPerformed
        ControladorSistema.iniciarProductos();
    }//GEN-LAST:event_MenuProductosActionPerformed

    private void menuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuariosActionPerformed
        ControladorSistema.iniciarUsuarios();
    }//GEN-LAST:event_menuUsuariosActionPerformed

    private void menuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentasActionPerformed
        ControladorSistema.iniciarVentas();
    }//GEN-LAST:event_menuVentasActionPerformed

    private void menuBitacorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBitacorasActionPerformed
        ControladorSistema.iniciarBitacora();
    }//GEN-LAST:event_menuBitacorasActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        ControladorSistema.Salir();
    }//GEN-LAST:event_menuSalirActionPerformed
    
    private void menuCerrarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarSActionPerformed
        ControladorSistema.cerrarSesion();

    }//GEN-LAST:event_menuCerrarSActionPerformed

    private void btnClientesActivarDesactivar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActivarDesactivar1ActionPerformed
        ControladorClientes.activarDesactivar();
    }//GEN-LAST:event_btnClientesActivarDesactivar1ActionPerformed

    private void btnClientesEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesEliminarActionPerformed
        ControladorClientes.eliminar();
    }//GEN-LAST:event_btnClientesEliminarActionPerformed

    private void btnClientesLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesLimpiarActionPerformed
        ControladorClientes.limpiar();
    }//GEN-LAST:event_btnClientesLimpiarActionPerformed

    private void btnClientesActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActualizarActionPerformed
        ControladorClientes.actualizar();
    }//GEN-LAST:event_btnClientesActualizarActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        ControladorClientes.elegirClientes(tblClientes.rowAtPoint(evt.getPoint()));
    }//GEN-LAST:event_tblClientesMouseClicked

    private void btnClientesRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesRegistrarActionPerformed
        ControladorClientes.registrar();
    }//GEN-LAST:event_btnClientesRegistrarActionPerformed

    private void btmBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmBBuscarActionPerformed
  ControladorBitacora.buscar();
    }//GEN-LAST:event_btmBBuscarActionPerformed

    private void cbxBitacoraSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBitacoraSeccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxBitacoraSeccionActionPerformed

    private void btnUsuariosEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosEstadoActionPerformed
        ControladorUsuarios.activarDesactivar();
    }//GEN-LAST:event_btnUsuariosEstadoActionPerformed

    private void txtUsuariosEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuariosEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuariosEstadoActionPerformed

    private void btnUsuariosModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosModificarActionPerformed
        ControladorUsuarios.modificar();
    }//GEN-LAST:event_btnUsuariosModificarActionPerformed

    private void btnUsuariosLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosLimpiarActionPerformed
        ControladorUsuarios.limpiar();
    }//GEN-LAST:event_btnUsuariosLimpiarActionPerformed

    private void btnUsuariosRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosRegistrarActionPerformed
        ControladorUsuarios.registrar();
    }//GEN-LAST:event_btnUsuariosRegistrarActionPerformed

    private void txtUsuariosUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuariosUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuariosUsuarioActionPerformed

    private void txtUsuariosIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuariosIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuariosIdActionPerformed

    private void txtUsuariosContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuariosContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuariosContrasenaActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        ControladorUsuarios.elegirUsuarios(tblUsuarios.rowAtPoint(evt.getPoint()));
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btnSistemaNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaNuevaVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSistemaNuevaVentaActionPerformed

    private void btnSistemaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaClientesActionPerformed
        ControladorSistema.iniciarClientes();
    }//GEN-LAST:event_btnSistemaClientesActionPerformed

    private void btnSistemaBitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaBitacoraActionPerformed
        ControladorSistema.iniciarBitacora();
    }//GEN-LAST:event_btnSistemaBitacoraActionPerformed

    private void btnSistemaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaProductosActionPerformed
        ControladorSistema.iniciarProductos();
    }//GEN-LAST:event_btnSistemaProductosActionPerformed

    private void btnSistemaUsusariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaUsusariosActionPerformed
        ControladorSistema.iniciarUsuarios();
    }//GEN-LAST:event_btnSistemaUsusariosActionPerformed

    private void btnSistemaVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaVentasActionPerformed
        ControladorSistema.iniciarVentas();
    }//GEN-LAST:event_btnSistemaVentasActionPerformed

    private void CbxBitacoraAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxBitacoraAccionActionPerformed

    }//GEN-LAST:event_CbxBitacoraAccionActionPerformed

    public boolean isCbxBitacoraAccio() {
        return CbxBitacoraAccio;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImprovementVistaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImprovementVistaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImprovementVistaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImprovementVistaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImprovementVistaSistema().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BitacoraPanel;
    private javax.swing.JComboBox<String> CbxBitacoraAccion;
    private javax.swing.JLabel LOGO;
    private javax.swing.JMenuItem MenuProductos;
    private javax.swing.JPanel UsuariosPanel;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btmBBuscar;
    private javax.swing.JPanel btnBitacoraBuscar;
    private javax.swing.JButton btnClientesActivarDesactivar1;
    private javax.swing.JButton btnClientesActualizar;
    private javax.swing.JButton btnClientesEliminar;
    private javax.swing.JButton btnClientesLimpiar;
    private javax.swing.JButton btnClientesRegistrar;
    private javax.swing.JButton btnSistemaBitacora;
    private javax.swing.JButton btnSistemaClientes;
    private javax.swing.JButton btnSistemaNuevaVenta;
    private javax.swing.JButton btnSistemaProductos;
    private javax.swing.JButton btnSistemaUsusarios;
    private javax.swing.JButton btnSistemaVentas;
    private javax.swing.JButton btnUsuariosEstado;
    private javax.swing.JButton btnUsuariosLimpiar;
    private javax.swing.JButton btnUsuariosModificar;
    private javax.swing.JButton btnUsuariosRegistrar;
    private javax.swing.JComboBox<String> cbxBitacoraSeccion;
    private javax.swing.JPanel clientesPanel;
    private javax.swing.JPanel columaPanel;
    private javax.swing.JPanel containerData;
    private javax.swing.JPanel contenedorDatos;
    private com.toedter.calendar.JDateChooser dateBFinal;
    private com.toedter.calendar.JDateChooser dateBiInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSistemaTitulo;
    private javax.swing.JMenuItem menuBitacoras;
    private javax.swing.JMenuItem menuCerrarS;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenuItem menuUsuarios;
    private javax.swing.JMenuItem menuVentas;
    private javax.swing.JPanel nuevaVentaPanel;
    private javax.swing.JPanel productosPanel;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JPanel tituloPanel;
    private javax.swing.JTextField txtClientesApellidoMaterno;
    private javax.swing.JTextField txtClientesApellidoPaterno;
    private javax.swing.JTextField txtClientesCorreo;
    private javax.swing.JTextField txtClientesEstado;
    private javax.swing.JTextField txtClientesId;
    private javax.swing.JTextField txtClientesNombre;
    private javax.swing.JTextField txtClientesRfc;
    private javax.swing.JTextField txtClientesTelefono;
    private javax.swing.JTextField txtUsuariosApellidoMaterno;
    private javax.swing.JTextField txtUsuariosApellidoPaterno;
    private javax.swing.JPasswordField txtUsuariosContrasena;
    private javax.swing.JTextField txtUsuariosEstado;
    private javax.swing.JTextField txtUsuariosId;
    private javax.swing.JTextField txtUsuariosNombre;
    private javax.swing.JTextField txtUsuariosUsuario;
    private javax.swing.JPanel ventasPanel;
    private javax.swing.JTabbedPane vistasMultiple;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTabbedPane getVistasMultiple() {
        return vistasMultiple;
    }
    
    public javax.swing.JTextField getTxtUsuariosApellidoMaterno() {
        return txtUsuariosApellidoMaterno;
    }
    
    public javax.swing.JTextField getTxtUsuariosApellidoPaterno() {
        return txtUsuariosApellidoPaterno;
    }
    
    public javax.swing.JPasswordField getTxtUsuariosContrasena() {
        return txtUsuariosContrasena;
    }
    
    public javax.swing.JTextField getTxtUsuariosId() {
        return txtUsuariosId;
    }
    
    public javax.swing.JTextField getTxtUsuariosNombre() {
        return txtUsuariosNombre;
    }
    
    public javax.swing.JTextField getTxtUsuariosUsuario() {
        return txtUsuariosUsuario;
    }
    
    public javax.swing.JTable getTblUsuarios() {
        return tblUsuarios;
    }
    
    public javax.swing.JButton getBtnUsuariosLimpiar() {
        return btnUsuariosLimpiar;
    }
    
    public javax.swing.JButton getBtnUsuariosRegistrar() {
        return btnUsuariosRegistrar;
    }
    
    public javax.swing.JTextField getTxtUsuariosEstado() {
        return txtUsuariosEstado;
    }
    
    public javax.swing.JTextField getTxtClientesApellidoMaterno() {
        return txtClientesApellidoMaterno;
    }
    
    public javax.swing.JTextField getTxtClientesApellidoPaterno() {
        return txtClientesApellidoPaterno;
    }
    
    public javax.swing.JTextField getTxtClientesCorreo() {
        return txtClientesCorreo;
    }
    
    public javax.swing.JTextField getTxtClientesEstado() {
        return txtClientesEstado;
    }
    
    public javax.swing.JTextField getTxtClientesId() {
        return txtClientesId;
    }
    
    public javax.swing.JTextField getTxtClientesNombre() {
        return txtClientesNombre;
    }
    
    public javax.swing.JTextField getTxtClientesRfc() {
        return txtClientesRfc;
    }
    
    public javax.swing.JTextField getTxtClientesTelefono() {
        return txtClientesTelefono;
    }
    
    public javax.swing.JTable getTblClientes() {
        return tblClientes;
    }

    public javax.swing.JComboBox<String> getCbxBitacoraAccion() {
        return CbxBitacoraAccion;
    }

    public javax.swing.JComboBox<String> getCbxBitacoraSeccion() {
        return cbxBitacoraSeccion;
    }
    
}
